// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpiPxed4q9XGS_VzVM6f4RFMg_1_itNU',
    appId: '1:759364394351:web:f92532e6485802bda4dc9a',
    messagingSenderId: '759364394351',
    projectId: 'toasties-kitahack-2024',
    authDomain: 'toasties-kitahack-2024.firebaseapp.com',
    storageBucket: 'toasties-kitahack-2024.appspot.com',
    measurementId: 'G-C4XZ1138GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj1ojGvNVPsRbJ41C9GFeXk3HITd0p6nY',
    appId: '1:759364394351:android:c65f5849c4fedb4da4dc9a',
    messagingSenderId: '759364394351',
    projectId: 'toasties-kitahack-2024',
    storageBucket: 'toasties-kitahack-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3f39_01wrfIm0iC7TBRTXl9IhBgTAW-k',
    appId: '1:759364394351:ios:f8daa2a6e95f9e13a4dc9a',
    messagingSenderId: '759364394351',
    projectId: 'toasties-kitahack-2024',
    storageBucket: 'toasties-kitahack-2024.appspot.com',
    iosBundleId: 'com.example.toastiesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3f39_01wrfIm0iC7TBRTXl9IhBgTAW-k',
    appId: '1:759364394351:ios:568ad8b35939de0aa4dc9a',
    messagingSenderId: '759364394351',
    projectId: 'toasties-kitahack-2024',
    storageBucket: 'toasties-kitahack-2024.appspot.com',
    iosBundleId: 'com.example.toastiesFlutter.RunnerTests',
  );
}
